In [ ]:
import sqlite3

conn = sqlite3.connect('sukh.db')

# Creating a cursor object
cursor = conn.cursor()

In [ ]:
cursor.execute('''
CREATE TABLE IF NOT EXISTS sukh (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    age INTEGER,
    grade TEXT
)
''')
conn.commit()
print("Table created successfully.")

In [ ]:
def insert_student(name, age, grade):
    cursor.execute("INSERT INTO sukh (name, age, grade) VALUES (?, ?, ?)", (name, age, grade))
    conn.commit()
    print("Student inserted successfully.")


insert_student('sukh', 20, 'A')
insert_student('harshita', 22, 'B')

In [ ]:
def fetch_students():
    cursor.execute("SELECT * FROM sukh")
    rows = cursor.fetchall()
    for row in rows:
        print(row)


fetch_students()

In [ ]:
def update_student(student_id, new_name, new_age, new_grade):
    cursor.execute("UPDATE sukh SET name=?, age=?, grade=? WHERE id=?", (new_name, new_age, new_grade, student_id))
    conn.commit()
    print("Student updated successfully.")
update_student(1, 'Riya Sharma', 21, 'A+')

In [ ]:
def delete_student(student_id):
    cursor.execute("DELETE FROM sukh WHERE id=?", (student_id,))
    conn.commit()
    print("Student deleted successfully.")


delete_student(2)

In [ ]:
fetch_students()

In [ ]:
conn.close()
print("Database connection closed.")

In [ ]:
# numpy

In [ ]:
import numpy as np

In [3]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([[1, 2], [3, 4]])
print(a)
print(b)

[1 2 3]
[[1 2]
 [3 4]]


In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)

(2, 3)
6
2
int64


In [5]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a.reshape(2, 3))

[[1 2 3]
 [4 5 6]]


In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1])
print(arr[1:4])

In [6]:
print(np.zeros((2, 3)))
print(np.ones((3, 3)))
print(np.eye(3, 3))
print(np.full((2, 2), 7))
print(np.arange(1, 10, 4))
print(np.linspace(1, 5, 4))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[7 7]
 [7 7]]
[1 5 9]
[1.         2.33333333 3.66666667 5.        ]


In [7]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(a * b)
print(a ** 2)
print(np.sqrt(a))
print(np.mean(a))

[5 7 9]
[ 4 10 18]
[1 4 9]
[1.         1.41421356 1.73205081]
2.0


In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.sum(arr, axis = 0))
print(np.sum(arr, axis = 1))

21
1
6
[5 7 9]
[ 6 15]


In [9]:
arr = np.array([[1, 2], [3, 4]])
print(arr.flatten())

[1 2 3 4]


In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


In [11]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[2, 0], [1, 2]])
print(np.dot(a, b))

[[ 4  4]
 [10  8]]


In [ ]:
# NumPy Coding Questions

In [12]:
# Create a NumPy array of integers from 0 to 10.
arr1 = np.arange(0, 11)
print("Array from 0 to 10:\n", arr1)

Array from 0 to 10:
 [ 0  1  2  3  4  5  6  7  8  9 10]


In [13]:
# Create an array of 10 zeros and change the 5th value to 1.
arr2 = np.zeros(10, dtype=int)
arr2[4] = 1     
print("\nArray of zeros with 5th element as 1:\n", arr2)


Array of zeros with 5th element as 1:
 [0 0 0 0 1 0 0 0 0 0]


In [14]:
# Generate an array of 10 ones.
arr3 = np.ones(10, dtype=int)
print("\nArray of 10 ones:\n", arr3)


Array of 10 ones:
 [1 1 1 1 1 1 1 1 1 1]


In [15]:
# Create a 1D array of 20 equally spaced numbers between 0 and 1.
arr4 = np.linspace(0, 1, 20)
print("\n20 equally spaced numbers between 0 and 1:\n", arr4)


20 equally spaced numbers between 0 and 1:
 [0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [16]:
# Create a 3x3 identity matrix.
arr5 = np.eye(3)
print("\n3x3 Identity matrix:\n", arr5)


3x3 Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
# Create a 4x4 matrix with values from 0 to 15.
arr6 = np.arange(16).reshape(4,4)
print("\n4x4 matrix from 0 to 15:\n", arr6)


4x4 matrix from 0 to 15:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [18]:
# Generate a 5x5 matrix with random values.
arr7 = np.random.rand(5,5)
print("\n5x5 random matrix:\n", arr7)


5x5 random matrix:
 [[0.47611321 0.68215812 0.87603555 0.25493969 0.01362819]
 [0.33230994 0.07245146 0.55517771 0.49425953 0.23711839]
 [0.89522632 0.6477574  0.33276169 0.09062778 0.53448453]
 [0.02503173 0.06515719 0.36473368 0.89620138 0.81014089]
 [0.55615399 0.80001157 0.94796207 0.30241761 0.07734377]]


In [19]:
# Reverse the elements of an array.
arr8 = np.array([1,2,3,4,5])
reversed_arr8 = arr8[::-1]
print("\nReversed array:\n", reversed_arr8)


Reversed array:
 [5 4 3 2 1]


In [20]:
# Flatten a 2D array to 1D.
arr9 = np.array([[1,2],[3,4],[5,6]])
flattened_arr9 = arr9.flatten()
print("\nFlattened array:\n", flattened_arr9)


Flattened array:
 [1 2 3 4 5 6]


In [21]:
# Extract even numbers from an array.
arr10 = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = arr10[arr10 % 2 == 0]
print("\nEven numbers from array:\n", even_numbers)


Even numbers from array:
 [ 2  4  6  8 10]
